version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: vivy
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vivy-chat
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    ports:
      - "6079:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
